/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "sys.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0     (GUI_ID_USER + 0x01)
#define ID_BUTTON_0     (GUI_ID_USER + 0x05)
#define ID_BUTTON_1     (GUI_ID_USER + 0x06)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Dialog", 0,30, 5,260, 230, FRAMEWIN_CF_MOVEABLE,0 },
{ BUTTON_CreateIndirect, "OK", GUI_ID_OK, 100, 5, 60, 20 }, 
{ BUTTON_CreateIndirect,"Cancel", GUI_ID_CANCEL,100, 30, 60, 20 },
{ TEXT_CreateIndirect,"LED1",0,10, 55, 48, 15, TEXT_CF_LEFT   },
{ TEXT_CreateIndirect,"LED2", 0, 10, 80, 48, 15, TEXT_CF_RIGHT },
  // USER START (Optionally insert additional widgets)
  // USER END
};
GUI_ConstString  _apListBox[] = {
	"chinese",
	"japan",
	"english"
};
/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {

	WM_HWIN hWin= pMsg->hWin;
	WM_HWIN htem;
	int NCode,Id;
	static u8 flag1 = 0,flag2 = 0;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
    //
    // Initialization of 'Framewin'
    //
   case WM_INIT_DIALOG: //WM_INIT_DIALOG ??,????????
				htem=WM_GetDialogItem(hWin,GUI_ID_OK);
				BUTTON_SetBkColor(htem,BUTTON_CI_UNPRESSED,GUI_BLACK);
				BUTTON_SetTextAlign(htem,GUI_TA_HCENTER);
				BUTTON_SetText(htem,"LED1_OFF");
	 
	 			htem=WM_GetDialogItem(hWin,GUI_ID_CANCEL);
				BUTTON_SetBkColor(htem,BUTTON_CI_UNPRESSED,GUI_BLACK);
				BUTTON_SetTextAlign(htem,GUI_TA_HCENTER);
				BUTTON_SetText(htem,"LED2_OFF");


				break;
  // USER START (Optionally insert additional message handling)
  // USER END
		case WM_NOTIFY_PARENT:                //(1)
				Id= WM_GetId(pMsg->hWinSrc);     //????? ID ?  (2)
				NCode = pMsg->Data.v;              //????      (3)
				switch (NCode) 
				{
					case WM_NOTIFICATION_CLICKED:
						if(Id == GUI_ID_OK){
							htem=WM_GetDialogItem(hWin,GUI_ID_OK);
				BUTTON_SetBkColor(htem,BUTTON_CI_UNPRESSED,GUI_GREEN);
				BUTTON_SetTextAlign(htem,GUI_TA_HCENTER);
				BUTTON_SetText(htem,"LED2_ON");
						}else{
							htem=WM_GetDialogItem(hWin,GUI_ID_CANCEL);
				BUTTON_SetBkColor(htem,BUTTON_CI_UNPRESSED,GUI_GREEN);
				BUTTON_SetTextAlign(htem,GUI_TA_HCENTER);
				BUTTON_SetText(htem,"LED2_ON");
						}
					case WM_NOTIFICATION_RELEASED:   //?????  (4)
					if (Id == GUI_ID_OK)         //OK ??  (5)
					{        
						htem=WM_GetDialogItem(hWin,GUI_ID_OK);
						flag1 = ~flag1;
						PAout(8)=flag1?0:1;
						flag1?BUTTON_SetText(htem,"LED1_ON"):BUTTON_SetText(htem,"LED1_OFF");
					}
					if (Id == GUI_ID_CANCEL)      //CANCEL ??  (6)
					{     
						htem=WM_GetDialogItem(hWin,GUI_ID_CANCEL);
						flag2 = ~flag2;
						PDout(2)=flag2?0:1;
						flag2?BUTTON_SetText(htem,"LED2_ON"):BUTTON_SetText(htem,"LED2_OFF");
					}
					break;
				}
				break;
		default:
		WM_DefaultProc(pMsg);
	}
}
static void _cbBkcallback(WM_MESSAGE *pMsg)
{
	switch(pMsg->MsgId)
	{
		case WM_PAINT:
			GUI_SetBkColor(GUI_BLACK);
		GUI_Clear();break;
		default:
			WM_DefaultProc(pMsg);
	}
}
/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
WM_HWIN CreateFramewin(void) {
  WM_HWIN hWin;
	PROGBAR_Handle hprogbar;
	//换肤
	BUTTON_SetDefaultSkin(BUTTON_SKIN_FLEX);
	FRAMEWIN_SetDefaultSkin(FRAMEWIN_SKIN_FLEX);
//	HEADER_SetDefaultSkin(HEADER_SKIN_FLEX);
//	MENU_SetDefaultSkin(MENU_SKIN_FLEX);
//	MULTIPAGE_SetDefaultSkin(MULTIPAGE_SKIN_FLEX);
	PROGBAR_SetDefaultSkin(PROGBAR_SKIN_FLEX);

	hprogbar = PROGBAR_Create(0,0,100,10,WM_CF_SHOW);
	PROGBAR_SetBarColor(hprogbar,1,GUI_GREEN);
	PROGBAR_SetBarColor(hprogbar,0,GUI_RED);
	PROGBAR_SetValue(hprogbar,70);
	
	WM_SetCallback(WM_HBKWIN,_cbBkcallback);
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);//非阻塞模式
	//若使用阻塞模式，则应使用GUI_ExecDialogBox()
	
	
	while(1){
	GUI_Delay(50);
	}
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
